apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit737-task6c-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit737-task6c-app
  template:
    metadata:
      labels:
        app: sit737-task6c-app
    spec:
      containers:
        - name: sit737-task6c-container
          image: sit737-task6c-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000